### ISSUE TITLE
Error message at setup in Home Assistant 2023.5.3

### ISSUE THREAD

**Issue by dajomas** [denkyem/home-assistant-moonraker#13]
Hi,

I just upgraded Home Assistant Core from 2023.4.5 to 2023.5.3 and now, I get the following error message:
```
2023-05-17 09:16:48.373 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry BTT-CB1 for moonraker
Traceback (most recent call last):
  File "/srv/Python-3.10.10/HASS-2023.5.3/lib/python3.10/site-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/moonraker/__init__.py", line 29, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

Aparently the ```async_setup_platforms``` function was marked deprecated a while back and now in version 2023.5.X it has actually been removed. The integration should use the ```await_async_forward_entry_setups``` instead if ```async_setup_platforms```

I installed the integration via the "Settings" => "Devices & Services" => "+ Add integration" button (searched for moonraker and entered the host of my Mainsail/moonraker/klipper host)

Can you please fix this issue? Thanx!

**Comment by dajomas** [comment]
Hmmmm, I think I posted this issue to the wrong repository. My apologies.
